<?php
if(PHP_SAPI!=='cli'){http_response_code(403);exit('CLI only');}
$_GET['refresh']='1';ob_start();include __DIR__.'/garden_feed.php';$raw=ob_get_clean();$data=json_decode($raw,true)?:[];$channels=$data['result']??[];
const WORKERS=24; const TIMEOUT=6;
function cat($n){$n=strtolower(trim(preg_replace('/\s*(\(?((720|1080)p|4k|hd|sd)\)?|\[((720|1080)p|4k|hd|sd)\])\s*$/i','',$n)));$m=['News'=>['news','aaj tak','abp'],'Movies'=>['movie','cinema','film'],'Music'=>['music','9xm','mtv','song'],'Sports'=>['sport','cricket','football','soccer','tennis','willow'],'Entertainment'=>['entertainment','comedy','drama','serial','show'],'Lifestyle'=>['lifestyle','fashion','travel','cooking'],'Infotainment'=>['discovery','history','documentary','education','knowledge'],'Science'=>['science','technology','tech','space','nature'],'Kids'=>['kids','cartoon','animation','junior','pogo','nick'],'Business'=>['cnbc','business','finance','et now'],'Doordarshan'=>['dd national','dd news','dd india','dd sports','doordarshan']];foreach($m as $c=>$xs)foreach($xs as $x)if(str_contains($n,$x))return $c;return 'Non Jio';}
function write_m3u($file,$channels){$f=fopen($file,'wb');fwrite($f,"#EXTM3U\n");foreach($channels as $c){$n=$c['name']??'Channel';$u=$c['url']??'';if($u==='')continue;$l=$c['logo']??'';$g=cat($n);$lang=$c['lang']??'All';fwrite($f,sprintf("#EXTINF:-1 tvg-logo=\"%s\" group-title=\"%s\" tvg-language=\"%s\",%s\n%s\n",htmlspecialchars($l,ENT_QUOTES),$g,htmlspecialchars($lang,ENT_QUOTES),$n,$u));}fclose($f);}
$mh=curl_multi_init();$map=[];$working=[];$bad=[];$next=0;$total=count($channels);
while($next<$total||$map){while($next<$total&&count($map)<WORKERS){$c=$channels[$next++];$u=$c['url']??'';if(!filter_var($u,FILTER_VALIDATE_URL)){$bad[]=$c;continue;}$h=curl_init($u);curl_setopt_array($h,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_RANGE=>'0-8191',CURLOPT_CONNECTTIMEOUT=>3,CURLOPT_TIMEOUT=>TIMEOUT,CURLOPT_USERAGENT=>'Mozilla/5.0 GardenPlaylist/1.0',CURLOPT_SSL_VERIFYPEER=>false,CURLOPT_SSL_VERIFYHOST=>false]);curl_multi_add_handle($mh,$h);$map[(int)$h]=[$h,$c];}
do{$rc=curl_multi_exec($mh,$running);}while($rc===CURLM_CALL_MULTI_PERFORM);if($running)curl_multi_select($mh,0.5);while($info=curl_multi_info_read($mh)){$h=$info['handle'];$c=$map[(int)$h][1];$body=curl_multi_getcontent($h);$code=(int)curl_getinfo($h,CURLINFO_HTTP_CODE);$ok=$code>=200&&$code<400&&strlen($body)>0;if($ok&&str_contains(strtolower($c['url']??''),'.m3u8'))$ok=str_contains($body,'#EXTM3U');if($ok)$working[]=$c;else$bad[]=$c;curl_multi_remove_handle($mh,$h);curl_close($h);unset($map[(int)$h]);}}
curl_multi_close($mh);write_m3u(__DIR__.'/working.m3u',$working);write_m3u(__DIR__.'/non_working.m3u',$bad);file_put_contents(__DIR__.'/status.json',json_encode(['generated_at'=>gmdate('c'),'total'=>$total,'working'=>count($working),'non_working'=>count($bad)],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));echo "TOTAL $total | WORKING ".count($working)." | NON-WORKING ".count($bad)."\n";
